services:
  postgres:
    image: postgres:16
    container_name: teamops-postgres
    environment:
      POSTGRES_USER: teamops
      POSTGRES_PASSWORD: teamops
      POSTGRES_DB: teamops_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_teamops:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teamops -d teamops_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata_teamops:
