spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/teamops_db
    username: teamops
    password: teamops
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/teamops_db
    user: teamops
    password: teamops
    schemas: public
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG