spring:
  application:
    name: teamops
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/teamops?sslmode=disable
    username: teamops
    password: teamops
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        show_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/docs
