spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/teamops_db
    username: teamops
    password: teamops
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # sem 'dialect' (o Hibernate infere)
        jdbc:
          time_zone: UTC
        format_sql: true
        show_sql: true   # útil em dev

  flyway:
    enabled: true
    # Se for MESMO banco da datasource acima, pode omitir url/user/password
    # url: jdbc:postgresql://localhost:5433/teamops_db
    # user: teamops
    # password: teamops
    schemas: public
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    enabled: true
    path: /v1/docs
    try-it-out-enabled: true
    display-request-duration: true

logging:
  level:
    org.springframework.security: DEBUG
