name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: teamops
          POSTGRES_PASSWORD: teamops
          POSTGRES_DB: teamops_test
        ports: ["5433:5432"]
        options: >-
          --health-cmd="pg_isready -U teamops -d teamops_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    env:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/teamops_test
      SPRING_DATASOURCE_USERNAME: teamops
      SPRING_DATASOURCE_PASSWORD: teamops
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SECURITY_JWT_SECRET: raw:THIS_is_a_very_long_and_safe_TEST_secret_key_1234567890
      MAVEN_OPTS: -Dmaven.test.redirectTestOutputToFile=false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build & Test
        run: mvn -B -ntp clean verify

